package dev.alvo.pieria.code;

import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Writes/reads the structured payload of a code-narrative summary memory (see
 * {@code CodeSummarizationService}). Like {@link CodePayload}, kept tolerant and dependency-free —
 * the payload is generated by us with a fixed shape, and the summarizer only needs the {@code hash}
 * back to decide whether the summarized code has changed.
 */
public final class CodeSummaryPayload {

  private static final Pattern HASH = Pattern.compile("\"hash\"\\s*:\\s*\"([^\"]*)\"");

  private CodeSummaryPayload() {
  }

  /**
   * The payload JSON: {@code {"source":"code-summary","level":…,"path":…,"hash":…}} with fixed key
   * order; {@code path} is omitted when null (the architecture overview has no path).
   */
  public static String write(String level, String path, String hash) {
    StringBuilder sb = new StringBuilder();
    sb.append("{\"source\":\"code-summary\"");
    sb.append(",\"level\":\"").append(esc(level)).append('"');
    if (path != null) {
      sb.append(",\"path\":\"").append(esc(path)).append('"');
    }
    sb.append(",\"hash\":\"").append(esc(hash)).append('"');
    sb.append('}');
    return sb.toString();
  }

  /**
   * The {@code payload.hash} value, or empty when absent.
   */
  public static Optional<String> hash(String payload) {
    if (payload == null || payload.isEmpty()) {
      return Optional.empty();
    }
    Matcher m = HASH.matcher(payload);
    return m.find() ? Optional.of(m.group(1)) : Optional.empty();
  }

  private static String esc(String s) {
    if (s == null) {
      return "";
    }
    StringBuilder b = new StringBuilder(s.length());
    for (int i = 0; i < s.length(); i++) {
      char c = s.charAt(i);
      switch (c) {
        case '"' -> b.append("\\\"");
        case '\\' -> b.append("\\\\");
        case '\n' -> b.append("\\n");
        case '\r' -> b.append("\\r");
        case '\t' -> b.append("\\t");
        default -> {
          if (c < 0x20) {
            b.append(String.format("\\u%04x", (int) c));
          } else {
            b.append(c);
          }
        }
      }
    }
    return b.toString();
  }
}
