package dev.alvo.pieria.code;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Reads the structured fields {@link CodeIndexingService} writes into a code-derived memory's
 * {@code payload} JSON. Kept tolerant and dependency-free (the payload is generated by us with a
 * fixed shape) so the retrieval channels can recover symbol-id provenance without a JSON library.
 */
public final class CodePayload {

  private static final Pattern SYMBOL_IDS_ARRAY = Pattern.compile("\"symbolIds\"\\s*:\\s*\\[([^]]*)]");
  private static final Pattern QUOTED = Pattern.compile("\"([^\"]*)\"");

  private CodePayload() {
  }

  /** The {@code payload.symbolIds} values, or an empty list when absent/non-code. */
  public static List<String> symbolIds(String payload) {
    if (payload == null || payload.isEmpty()) {
      return List.of();
    }
    Matcher arr = SYMBOL_IDS_ARRAY.matcher(payload);
    if (!arr.find()) {
      return List.of();
    }
    List<String> ids = new ArrayList<>();
    Matcher q = QUOTED.matcher(arr.group(1));
    while (q.find()) {
      String id = q.group(1);
      if (!id.isBlank()) {
        ids.add(id);
      }
    }
    return ids;
  }
}
